const constituencies = [
  "Nerela",
  "Burari",
  "Timarpur",
  "Adarsh Nagar",
  "Badli",
  "Rithala",
  "Bawana",
  "Mundka",
  "Kirari",
  "Sultanpur Majra",
  "Nangloi Jat",
  "Mangol Puri",
  "Rohini",
  "Shalimar Bagh",
  "Shakur Basti",
  "Tri Nagar",
  "Wazirpur",
  "Model Town",
  "Sadar Bazar",
  "Chandni Chowk",
  "Matia Mahal",
  "Ballimaran",
  "Karol Bagh",
  "Patel Nagar",
  "Moti Nagar",
  "Madipur",
  "Rajouri Garden",
  "Hari Nagar",
  "Tilak Nagar",
  "Janakpuri",
  "Vikaspuri",
  "Uttam Nagar",
  "Dwarka",
  "Matiala",
  "Najafgarh",
  "Bijwasan",
  "Palam",
  "Delhi Cantt",
  "Rajinder Nagar",
  "New Delhi",
  "Jangpura",
  "Kasturba Nagar",
  "Malviya Nagar",
  "R K Puram",
  "Mehrauli",
  "Chhatarpur",
  "Deoli",
  "Ambedkar Nagar",
  "Sangam Vihar",
  "Greater Kailash",
  "Kalkaji",
  "Tughlakabad",
  "Badarpur",
  "Okhla",
  "Trilokpuri",
  "Kondli",
  "Patparganj",
  "Laxmi Nagar",
  "Vishwas Nagar",
  "Krishna Nagar",
  "Gandhi Nagar",
  "Shahdara",
  "Seema Puri",
  "Rohtas Nagar",
  "Seelampur",
  "Ghonda",
  "Babarpur",
  "Gokalpur",
  "Mustafabad",
  "Karawal Nagar",
];

const constituencyData = constituencies.map((name) => ({
  name,
  state: "Delhi",
  totalVotes: 0,
  candidates: ["673b172943ad5c35142192be"],
  won: "awaiting",
  __v: 0,
}));

console.log(constituencyData);
{
  name: "Hari Nagar";
  state: "Delhi";
  totalVotes: 0;
  candidates: ["673b172943ad5c35142192be"];
  won: "awaiting";
  __v: 0;
}

export const pathToConstituency = {
  path4081: "cns-narela",
  path3995: "cns-burari",
  path4103: "cns-timarpur",
  path4101: "cns-adarsh nagar",
  path4099: "cns-badli",
  path3997: "cns-rithala",
  path4083: "cns-bawana",
  path3197: "cns-mundka",
  path4001: "cns-kirari",
  path4087: "cns-sultanpur majra",
  path4089: "cns-nangloi jat",
  path4085: "cns-mangolpuri",
  path4003: "cns-rohini",
  path4005: "cns-shalimar bagh",
  path4009: "cns-shakur basti",
  path4095: "cns-tri nagar",
  path4097: "cns-wazirpur",
  path4105: "cns-model town",
  path4107: "cns-sadar bazar",
  path4113: "cns-chandni chowk",
  path4051: "cns-matia mahal",
  path3165: "cns-ballimaran",
  path4011: "cns-karol bagh",
  path4109: "cns-patel nagar",
  path4013: "cns-moti nagar",
  path4093: "cns-madipur",
  path4091: "cns-rajouri garden",
  path4015: "cns-hari nagar",
  path4017: "cns-tilak nagar",
  path4021: "cns-janakpuri",
  path4069: "cns-vikaspuri",
  path4071: "cns-uttam nagar",
  path4023: "cns-dwarka",
  path3183: "cns-matiala",
  path3181: "cns-najafgarh",
  path4025: "cns-bijwasan",
  path4027: "cns-palam",
  path4029: "cns-delhi cantt",
  path4073: "cns-rajinder nagar",
  path4075: "cns-new delhi",
  path3149: "cns-jangpura",
  path3147: "cns-kasturba nagar",
  path3145: "cns-malviya nagar",
  path4079: "cns-r k puram",
  path4063: "cns-mehrauli",
  path4061: "cns-chhatarpur",
  path3179: "cns-deoli",
  path3177: "cns-ambedkar nagar",
  path4031: "cns-sangam vihar",
  path4033: "cns-greater kailash",
  path3175: "cns-kalkaji",
  path4035: "cns-tughlakabad",
  path4047: "cns-badarpur",
  path4053: "cns-okhla",
  path4037: "cns-trilokpuri",
  path3171: "cns-kondli",
  path3169: "cns-patparganj",
  path3167: "cns-laxmi nagar",
  path3161: "cns-vishwas nagar",
  path4039: "cns-krishna nagar",
  path3163: "cns-gandhi nagar",
  path3173: "cns-shahdara",
  path3159: "cns-seemapuri",
  path3157: "cns-rohtas nagar",
  path3153: "cns-seelampur",
  path4041: "cns-ghonda",
  path4043: "cns-babarpur",
  path4049: "cns-gokalpur",
  path3155: "cns-mustafabad",
  path4045: "cns-karawal nagar",
};
